### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'E:\dev\null'

### ISSUE THREAD

**Issue by vipulwairagade** [zishone/oas-express-starter#41]
This is great and when I was trying to run this code to check everything, I am facing this issue. Can you help me with figuring out what is causing this issue ?

```
> oas-express-starter@0.1.0-development start E:\node-learn\boilerplate\oas-express-starter-master
> node dist/server.js

{"service":"oas-express-starter","version":"0.1.0-development","env":"development","hostname":"WJLP-1032","envConfig.ENV":"development","envConfig.HOSTNAME":"WJLP-1032","envConfig.APP_PORT":3000,"envConfig.DB_URI":"mongodb://127.0.0.1:27017","envConfig.DB_NAME":"oasDB","envConfig.LOGIN_SECRET":"login_secret    # Secret for generating JWT login tokens","envConfig.LOGIN_TTL":2592000,"timestamp":"2021-03-10T12:55:09.471Z","level":"debug","message":"Environment config"}
{"service":"oas-express-starter","version":"0.1.0-development","env":"development","hostname":"WJLP-1032","function.name":"Database.getConnection","function.arguments":[],"timestamp":"2021-03-10T12:55:09.478Z","level":"debug","message":"Function called"}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'E:\dev\null'
Emitted 'error' event on WriteStream instance at:
    at internal/fs/streams.js:361:12
    at FSReqCallback.oncomplete (fs.js:156:23) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'E:\\dev\\null'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oas-express-starter@0.1.0-development start: `node dist/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oas-express-starter@0.1.0-development start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vipulw\AppData\Roaming\npm-cache\_logs\2021-03-10T12_55_09_559Z-debug.log
```

Thanks in advance !

**Comment by zishone** [comment]
Hi @vipulwairagade 

Thank you for raising this issue 🙂 
I have merged the PR https://github.com/zishone/oas-express-starter/pull/42 to fix the issue you are having. 

The problem was that I had set the logger to stream to `/dev/null` as a default when no other transport has been added to the logger instance and because you were probably using windows, it could not find that path. You can see what I mean [here](https://github.com/zishone/oas-express-starter/blob/86f1181ef997ca1a0cbd1acb29e3e8487566376e/src/helpers/logger.ts#L19).

The resolution was to use a silent console transport instead [here](https://github.com/zishone/oas-express-starter/blob/master/src/helpers/logger.ts#L18).

Thanks for trying it out 😃 
I there is anything else, please let me know.

**Comment by vipulwairagade** [comment]
hi @zishone 

Thanks for the quick resolution of the issue. I actually searched in the directory for the path, but I don't know why no results were found when I did. But it's not giving me that error anymore.

But I am facing one error related to MongoDB. I tried fixing it but similar issue has been created on their official repository.

Should I create separate issue for that ?

**Comment by zishone** [comment]
Sure, please do :)

**Comment by vipulwairagade** [comment]
Done. We can close this issue btw.
